server:
  port: 8090
  servlet:
    session:
      timeout: 120m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ec^3?useSSL=false&serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: wayne
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /views/
      suffix: .html


snow:
  workerId: 1
  datacenterId: 1
  #sequenceBits



