server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ec^3?useSSL=false&amp;serverTimezone=GMT%2B8&amp;useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: wayne
    driver-class-name: com.mysql.cj.jdbc.Driver
